name: network
description: A networking library that prepares an http client to communicate with a remote server.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  collection: ^1.17.2
  dio: ^5.3.3
  equatable: ^2.0.5
  http_parser: ^4.0.2
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.6
  mockito: ^5.4.2
  test: ^1.24.7
  very_good_analysis: ^5.1.0
