name: resource
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  domain:
    path: ../domain
  # path: ^1.8.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  google_nav_bar: ^5.0.6
  firebase_auth:
  freezed:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
